name: Publish to GitHub Packages

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-alpha[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-beta[0-9]+"

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Publish package
        run: ./gradlew publishAllPublicationsToGithubPackagesRepository
        env:
          ORG_GRADLE_PROJECT_githubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_githubPackagesUsername: ${{ github.actor }}
